version: '3.7'
services:
    db:
        image: postgres:13
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=admin
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5551:5432'
        volumes: 
          - ./pg_data:/var/lib/postgresql/data
          - ./data:/tmp/data
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
